### ISSUE TITLE
Error: The getter 'Platform' isn't defined for the class 'X'

### ISSUE THREAD

**Issue by matteoberla** [WalletConnect/Web3ModalFlutter#117]
I'm receiving this at startup, i've tried to clear cache of packages but nothing seems to work

```
../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/services/explorer_service/explorer_service.dart:199:19: Error: The getter 'Platform' isn't defined for the class 'ExplorerService'.
 - 'ExplorerService' is from 'package:web3modal_flutter/services/explorer_service/explorer_service.dart' ('../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/services/explorer_service/explorer_service.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Platform'.
      final uri = Platform.isIOS
                  ^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/services/explorer_service/explorer_service.dart:463:13: Error: The getter 'Platform' isn't defined for the class 'ExplorerService'.
 - 'ExplorerService' is from 'package:web3modal_flutter/services/explorer_service/explorer_service.dart' ('../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/services/explorer_service/explorer_service.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Platform'.
        if (Platform.isIOS) {
            ^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/services/explorer_service/explorer_service.dart:465:20: Error: The getter 'Platform' isn't defined for the class 'ExplorerService'.
 - 'ExplorerService' is from 'package:web3modal_flutter/services/explorer_service/explorer_service.dart' ('../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/services/explorer_service/explorer_service.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Platform'.
        } else if (Platform.isAndroid) {
                   ^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/utils/platform/platform_utils.dart:9:9: Error: The getter 'Platform' isn't defined for the class 'PlatformUtils'.
 - 'PlatformUtils' is from 'package:web3modal_flutter/utils/platform/platform_utils.dart' ('../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/utils/platform/platform_utils.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Platform'.
    if (Platform.isAndroid) {
        ^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/utils/platform/platform_utils.dart:11:16: Error: The getter 'Platform' isn't defined for the class 'PlatformUtils'.
 - 'PlatformUtils' is from 'package:web3modal_flutter/utils/platform/platform_utils.dart' ('../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/utils/platform/platform_utils.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Platform'.
    } else if (Platform.isIOS) {
               ^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/utils/platform/platform_utils.dart:13:16: Error: The getter 'Platform' isn't defined for the class 'PlatformUtils'.
 - 'PlatformUtils' is from 'package:web3modal_flutter/utils/platform/platform_utils.dart' ('../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/utils/platform/platform_utils.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Platform'.
    } else if (Platform.isLinux) {
               ^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/utils/platform/platform_utils.dart:15:16: Error: The getter 'Platform' isn't defined for the class 'PlatformUtils'.
 - 'PlatformUtils' is from 'package:web3modal_flutter/utils/platform/platform_utils.dart' ('../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/utils/platform/platform_utils.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Platform'.
    } else if (Platform.isMacOS) {
               ^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/utils/platform/platform_utils.dart:17:16: Error: The getter 'Platform' isn't defined for the class 'PlatformUtils'.
 - 'PlatformUtils' is from 'package:web3modal_flutter/utils/platform/platform_utils.dart' ('../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/utils/platform/platform_utils.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Platform'.
    } else if (Platform.isWindows) {
               ^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/utils/platform/platform_utils.dart:27:9: Error: The getter 'Platform' isn't defined for the class 'PlatformUtils'.
 - 'PlatformUtils' is from 'package:web3modal_flutter/utils/platform/platform_utils.dart' ('../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/utils/platform/platform_utils.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Platform'.
    if (Platform.isAndroid || Platform.isIOS) {
        ^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/utils/platform/platform_utils.dart:27:31: Error: The getter 'Platform' isn't defined for the class 'PlatformUtils'.
 - 'PlatformUtils' is from 'package:web3modal_flutter/utils/platform/platform_utils.dart' ('../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/utils/platform/platform_utils.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Platform'.
    if (Platform.isAndroid || Platform.isIOS) {
                              ^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/utils/platform/platform_utils.dart:29:16: Error: The getter 'Platform' isn't defined for the class 'PlatformUtils'.
 - 'PlatformUtils' is from 'package:web3modal_flutter/utils/platform/platform_utils.dart' ('../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/utils/platform/platform_utils.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Platform'.
    } else if (Platform.isLinux || Platform.isMacOS || Platform.isWindows) {
               ^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/utils/platform/platform_utils.dart:29:36: Error: The getter 'Platform' isn't defined for the class 'PlatformUtils'.
 - 'PlatformUtils' is from 'package:web3modal_flutter/utils/platform/platform_utils.dart' ('../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/utils/platform/platform_utils.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Platform'.
    } else if (Platform.isLinux || Platform.isMacOS || Platform.isWindows) {
                                   ^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/utils/platform/platform_utils.dart:29:56: Error: The getter 'Platform' isn't defined for the class 'PlatformUtils'.
 - 'PlatformUtils' is from 'package:web3modal_flutter/utils/platform/platform_utils.dart' ('../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/utils/platform/platform_utils.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Platform'.
    } else if (Platform.isLinux || Platform.isMacOS || Platform.isWindows) {
                                                       ^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/pages/get_wallet_page.dart:51:29: Error: The getter 'Platform' isn't defined for the class 'GetWalletPage'.
 - 'GetWalletPage' is from 'package:web3modal_flutter/pages/get_wallet_page.dart' ('../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/pages/get_wallet_page.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Platform'.
                final url = Platform.isIOS
                            ^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/widgets/lists/list_items/download_wallet_item.dart:22:9: Error: The getter 'Platform' isn't defined for the class 'DownloadWalletItem'.
 - 'DownloadWalletItem' is from 'package:web3modal_flutter/widgets/lists/list_items/download_wallet_item.dart' ('../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/widgets/lists/list_items/download_wallet_item.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Platform'.
    if (Platform.isIOS) {
        ^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/widgets/lists/list_items/download_wallet_item.dart:25:9: Error: The getter 'Platform' isn't defined for the class 'DownloadWalletItem'.
 - 'DownloadWalletItem' is from 'package:web3modal_flutter/widgets/lists/list_items/download_wallet_item.dart' ('../../../AppData/Local/Pub/Cache/hosted/pub.dev/web3modal_flutter-3.1.2/lib/widgets/lists/list_items/download_wallet_item.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Platform'.
    if (Platform.isAndroid) {
        ^^^^^^^^

```

**Comment by quetool** [comment]
Can you share your pubspec.yaml?

**Comment by matteoberla** [comment]
for sure

```
name: wallet_connect
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  web3modal_flutter: ^3.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```

**Comment by quetool** [comment]
This is weird, do you mind trying. If you open `pubspec.lock` what do you see under `web3modal_flutter:`?

**Comment by matteoberla** [comment]
```
  web3modal_flutter:
    dependency: "direct main"
    description:
      name: web3modal_flutter
      sha256: "73d007ad95919cecc108216e5b1a971fd3e1d50d6da8a7b9e2c96948eefc5c4b"
      url: "https://pub.dev"
    source: hosted
    version: "3.1.2"
```

**Comment by quetool** [comment]
Even more weird. We have the exact same dependency. Please try the following:

Delete everything under these folders:
```
/Users/{username}/.pub-cache/hosted-hashes/pub.dev/
/Users/{username}/.pub-cache/hosted/pub.dev/
/Users/{username}/.pub-cache/git/
/Users/{username}/.pub-cache/git/cache/
```

Then inside your project do:

```
flutter clean
flutter pub get -v
```

**Comment by matteoberla** [comment]
i've done it but nothing changed.
I'm trying to run it on web even if the package is not supported as i wanted to test the version from issue #108, but error occurs.
I remember that i've tried this package some times ago, another error occurred while testing on web, but this time compiling fails.

**Comment by quetool** [comment]
Oh man you should have said that. 😅 
**Web3Modal does not support web yet**. You can follow up in that thread/issue if you want but I can't be of help for web right now.

**Comment by matteoberla** [comment]
Yes i've followed but same issue happens on the other version.
I'm sure that some time ago i've used this package on web, the application was compiling correctly and there was another error when i was trying to use the connect wallet widget. so i'm a little confused on how to proceed

**Comment by quetool** [comment]
I can't help, Web3Modal has never supported web platforms, maybe you tried WalletConnectModalFlutter that it's a bit more simpler and my be running better in the web.

**Comment by asmodeoux** [comment]
You need to use `web3modal_flutter` package version that depends on `walletconnect_flutter_v2` of a version below `2.2.3`, in 2.2.3 they broke something so it doesn't launch in Web anymore.

You can use my fork if you wish, I fixed some other UI issue in Web there:
```
web3modal_flutter:
    git: 
      url: https://github.com/asmodeoux/Web3ModalFlutter.git
      ref: ptal
```
